name: expensemanage_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.1.4
  font_awesome_flutter: ^10.1.0
  flutter_switch: ^0.3.2
  sliding_switch: ^1.1.0
  local_auth:
  connectivity:
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
#  flutter_card_scanner_latest: ^1.0.5
  cached_network_image:
  http: ^0.13.5
  firebase_core: ^1.2.1
  firebase_messaging: ^13.0.4
  firebase_auth: ^3.6.3
#  flutter_local_notifications: ^11.0.1
  get_storage: ^2.0.3
  month_year_picker: ^0.2.0+2
  google_mlkit_object_detection: ^0.5.0
  url_launcher: ^6.1.6
#  image_picker: ^0.8.5+3
  camera:
  path_provider: ^2.0.11
#  credit_card_scanner: ^1.0.5
#  card_scanner: ^0.2.2
  intl: ^0.17.0
#  google_mlkit_text_recognition: ^0.4.0
#  ml_card_scanner: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
     - assets/ml/
     - assets/image/
     - assets/svg/
     - assets/gif/
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/font/Poppins-Light.ttf
           weight: 300
         - asset: assets/font/Poppins-Regular.ttf
           weight: 400
         - asset: assets/font/Poppins-Medium.ttf
           weight: 500
         - asset: assets/font/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/font/Poppins-Bold.ttf
           weight: 700
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
